name: ROS 1 dev test melodic
on:
  pull_request:
  push:
    branches:
      - ros1_dev
jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: melodic
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros1-distro: melodic